server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

indexing-settings:
  sites:
    - url: https://www.playback.ru/
      name: Playback.ru
    - url: https://nikoartgallery.com/
      name: Nikoartgallery.com

user-agent-settings:
  user: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
  referrer: http://www.google.com